// lib/web-studio/scaffold.js
// ============================================================
//  Lay down a minimal, token-driven Astro + Tailwind workspace for one site.
//  Pure fs, no agent calls. The creation pipeline calls this first; the agents
//  then fill src/pages + tokens; build.js compiles to dist/ (plain static).
//
//  Design choices baked in here (locked decision: Astro + Tailwind, static):
//   - Zero-JS-by-default static output.
//   - A SINGLE shared layout (Base.astro) so multi-page sites stay consistent.
//   - Design tokens as CSS custom properties — the one place the site themes from.
// ============================================================

const fs = require('fs');
const path = require('path');

function pkgJson(name) {
  const safe = String(name || 'aios-site').toLowerCase().replace(/[^a-z0-9-]/g, '-').replace(/^-+|-+$/g, '').slice(0, 40) || 'aios-site';
  return JSON.stringify({
    name: safe,
    type: 'module',
    private: true,
    version: '0.0.0',
    scripts: { build: 'astro build' },
    dependencies: {
      astro: '^4.16.0',
      '@astrojs/tailwind': '^5.1.0',
      tailwindcss: '^3.4.0',
    },
  }, null, 2) + '\n';
}

const ASTRO_CONFIG = `import { defineConfig } from 'astro/config';
import tailwind from '@astrojs/tailwind';

// Static output (Astro default) — emits plain HTML/CSS/JS to dist/. No server runtime.
export default defineConfig({
  integrations: [tailwind({ applyBaseStyles: false })],
  build: { format: 'directory' },
});
`;

const TAILWIND_CONFIG = `/** @type {import('tailwindcss').Config} */
export default {
  content: ['./src/**/*.{astro,html,js,jsx,ts,tsx,md,mdx}'],
  theme: {
    extend: {
      colors: { brand: 'var(--brand)', accent: 'var(--accent)', ink: 'var(--ink)', paper: 'var(--paper)' },
      fontFamily: { display: ['var(--font-display)'], body: ['var(--font-body)'] },
    },
  },
  plugins: [],
};
`;

// Design tokens as CSS custom properties — vibe-designer's palette/type lands here.
function tokensCss(tokens = {}, opts = {}) {
  const t = {
    brand: tokens.brand || '#4f46e5',
    accent: tokens.accent || '#f59e0b',
    ink: tokens.ink || '#0f172a',
    paper: tokens.paper || '#ffffff',
    fontDisplay: tokens.fontDisplay || "Georgia, 'Times New Roman', serif",
    fontBody: tokens.fontBody || "system-ui, -apple-system, Segoe UI, Roboto, sans-serif",
  };
  // Only allow a safe subset of chars into the token values (these are written into
  // CSS that the build serves) — defense against a hostile token from an imported brand.
  const clean = (v, fallback) => (/^[#a-zA-Z0-9 ,.'()\-_%]+$/.test(String(v)) ? String(v) : fallback);
  let css = `:root {
  --brand: ${clean(t.brand, '#4f46e5')};
  --accent: ${clean(t.accent, '#f59e0b')};
  --ink: ${clean(t.ink, '#0f172a')};
  --paper: ${clean(t.paper, '#ffffff')};
  --font-display: ${clean(t.fontDisplay, 'Georgia, serif')};
  --font-body: ${clean(t.fontBody, 'system-ui, sans-serif')};
}

@tailwind base;
@tailwind components;
@tailwind utilities;

html { color: var(--ink); background: var(--paper); font-family: var(--font-body); }
`;

  // Opt-in "liquid glass" surface utility — a single reusable frosted-panel class.
  // Never forced site-wide; callers add `.ws-glass` to whatever markup wants the look.
  if (opts && opts.theme === 'glass') {
    css += `
.ws-glass {
  background: rgba(255, 255, 255, 0.55);
  background: color-mix(in srgb, var(--paper) 55%, transparent);
  -webkit-backdrop-filter: blur(16px) saturate(160%);
  backdrop-filter: blur(16px) saturate(160%);
  border: 1px solid rgba(255, 255, 255, 0.35);
  border-radius: 1rem;
}

[data-theme="dark"] .ws-glass {
  background: rgba(15, 23, 42, 0.45);
  background: color-mix(in srgb, var(--ink) 55%, transparent);
  border: 1px solid rgba(255, 255, 255, 0.12);
}
`;
  }

  return css;
}

const BASE_LAYOUT = `---
// Shared layout for EVERY page — header, nav, footer live here once. Pages import it.
import '../styles/tokens.css';
const { title = 'Untitled', description = '', og = {} } = Astro.props;
---
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>{title}</title>
    {description && <meta name="description" content={description} />}
    <meta property="og:title" content={og.title ?? title} />
    {(og.description ?? description) && <meta property="og:description" content={og.description ?? description} />}
    <meta name="twitter:card" content="summary_large_image" />
  </head>
  <body class="min-h-screen flex flex-col">
    <slot />
  </body>
</html>
`;

const INDEX_PAGE = `---
import Base from '../layouts/Base.astro';
---
<Base title="New Site" description="Generated by AI OS Web Studio">
  <main class="flex-1 grid place-items-center p-16 text-center">
    <div>
      <h1 class="text-5xl font-display text-brand">Your site is being built</h1>
      <p class="mt-4 text-lg opacity-70">The Web Studio team is composing your pages.</p>
    </div>
  </main>
</Base>
`;

/**
 * Write the Astro + Tailwind skeleton into a workspace dir.
 * @param {string} dir  workspace root, e.g. .magent/artifacts/web-studio/<siteId>
 * @param {{siteName?: string, tokens?: object}} opts
 * @returns {{dir, srcDir}}
 */
function scaffoldWorkspace(dir, opts = {}) {
  const src = path.join(dir, 'src');
  for (const d of ['layouts', 'pages', 'components', 'styles']) {
    fs.mkdirSync(path.join(src, d), { recursive: true });
  }
  fs.mkdirSync(path.join(dir, 'public'), { recursive: true });

  fs.writeFileSync(path.join(dir, 'package.json'), pkgJson(opts.siteName));
  fs.writeFileSync(path.join(dir, 'astro.config.mjs'), ASTRO_CONFIG);
  fs.writeFileSync(path.join(dir, 'tailwind.config.mjs'), TAILWIND_CONFIG);
  fs.writeFileSync(path.join(dir, '.gitignore'), 'node_modules/\ndist/\n.astro/\n');
  fs.writeFileSync(path.join(src, 'styles', 'tokens.css'), tokensCss(opts.tokens));
  fs.writeFileSync(path.join(src, 'layouts', 'Base.astro'), BASE_LAYOUT);
  fs.writeFileSync(path.join(src, 'pages', 'index.astro'), INDEX_PAGE);

  return { dir, srcDir: src };
}

/**
 * Dark-mode toggle: scoped CSS + a static accessible button + a tiny vanilla-JS
 * snippet that applies/persists the theme. Brand/accent tokens are left untouched
 * so brand identity stays consistent between light and dark.
 * @returns {{toggleMarkup: string, style: string, script: string}}
 */
function darkModeSnippet() {
  const toggleMarkup = `<button type="button" class="ws-theme-toggle" aria-label="Toggle dark mode"><span aria-hidden="true">🌙</span></button>`;

  const style = `[data-theme="dark"] {
  --paper: #0f172a;
  --ink: #f8fafc;
}

.ws-theme-toggle {
  display: inline-flex;
  align-items: center;
  justify-content: center;
  width: 2.25rem;
  height: 2.25rem;
  padding: 0;
  border: 1px solid rgba(148, 163, 184, 0.35);
  border-radius: 9999px;
  background: transparent;
  color: var(--ink);
  font-size: 1rem;
  line-height: 1;
  cursor: pointer;
  transition: background-color 0.15s ease, border-color 0.15s ease;
}

.ws-theme-toggle:hover,
.ws-theme-toggle:focus-visible {
  background: rgba(148, 163, 184, 0.15);
}

.ws-theme-toggle:focus-visible {
  outline: 2px solid var(--brand);
  outline-offset: 2px;
}
`;

  const script = `(function () {
  var STORAGE_KEY = 'ws-theme';
  var root = document.documentElement;
  var saved = null;
  try { saved = localStorage.getItem(STORAGE_KEY); } catch (e) { saved = null; }
  if (saved === 'dark' || saved === 'light') {
    root.setAttribute('data-theme', saved);
  } else if (window.matchMedia && window.matchMedia('(prefers-color-scheme: dark)').matches) {
    root.setAttribute('data-theme', 'dark');
  }

  var toggle = document.querySelector('.ws-theme-toggle');
  if (toggle) {
    toggle.addEventListener('click', function () {
      var current = root.getAttribute('data-theme') === 'dark' ? 'dark' : 'light';
      var next = current === 'dark' ? 'light' : 'dark';
      root.setAttribute('data-theme', next);
      try { localStorage.setItem(STORAGE_KEY, next); } catch (e) {}
    });
  }
})();
`;

  return { toggleMarkup, style, script };
}

/**
 * Scroll-reveal + hover-lift micro-interactions. Fully inert (content visible,
 * no motion) unless the visitor's OS allows motion — see prefers-reduced-motion.
 * @returns {{style: string, script: string, sectionClass: string}}
 */
function motionSnippet() {
  const sectionClass = 'ws-reveal';

  const style = `.ws-reveal {
  opacity: 1;
  transform: none;
}

@media (prefers-reduced-motion: no-preference) {
  .ws-reveal {
    opacity: 0;
    transform: translateY(16px);
    transition: opacity 0.6s ease, transform 0.6s ease;
  }

  .ws-reveal.ws-reveal-visible {
    opacity: 1;
    transform: translateY(0);
  }
}

.ws-hover-lift {
  transition: transform 0.15s ease, box-shadow 0.15s ease;
}

@media (prefers-reduced-motion: no-preference) {
  .ws-hover-lift:hover {
    transform: translateY(-4px);
    box-shadow: 0 12px 24px -12px rgba(15, 23, 42, 0.35);
  }
}
`;

  const script = `(function () {
  var items = document.querySelectorAll('.ws-reveal');
  if (typeof IntersectionObserver === 'undefined') {
    items.forEach(function (el) { el.classList.add('ws-reveal-visible'); });
    return;
  }
  var observer = new IntersectionObserver(function (entries, obs) {
    entries.forEach(function (entry) {
      if (entry.isIntersecting) {
        entry.target.classList.add('ws-reveal-visible');
        obs.unobserve(entry.target);
      }
    });
  }, { threshold: 0.15 });
  items.forEach(function (el) { observer.observe(el); });
})();
`;

  return { style, script, sectionClass };
}

module.exports = { scaffoldWorkspace, tokensCss, darkModeSnippet, motionSnippet };
