// lib/web-studio/scaffold.js
// ============================================================
//  Lay down a minimal, token-driven Astro + Tailwind workspace for one site.
//  Pure fs, no agent calls. The creation pipeline calls this first; the agents
//  then fill src/pages + tokens; build.js compiles to dist/ (plain static).
//
//  Design choices baked in here (locked decision: Astro + Tailwind, static):
//   - Zero-JS-by-default static output.
//   - A SINGLE shared layout (Base.astro) so multi-page sites stay consistent.
//   - Design tokens as CSS custom properties — the one place the site themes from.
// ============================================================

const fs = require('fs');
const path = require('path');

function pkgJson(name) {
  const safe = String(name || 'aios-site').toLowerCase().replace(/[^a-z0-9-]/g, '-').replace(/^-+|-+$/g, '').slice(0, 40) || 'aios-site';
  return JSON.stringify({
    name: safe,
    type: 'module',
    private: true,
    version: '0.0.0',
    scripts: { build: 'astro build' },
    dependencies: {
      astro: '^4.16.0',
      '@astrojs/tailwind': '^5.1.0',
      tailwindcss: '^3.4.0',
    },
  }, null, 2) + '\n';
}

const ASTRO_CONFIG = `import { defineConfig } from 'astro/config';
import tailwind from '@astrojs/tailwind';

// Static output (Astro default) — emits plain HTML/CSS/JS to dist/. No server runtime.
export default defineConfig({
  integrations: [tailwind({ applyBaseStyles: false })],
  build: { format: 'directory' },
});
`;

const TAILWIND_CONFIG = `/** @type {import('tailwindcss').Config} */
export default {
  content: ['./src/**/*.{astro,html,js,jsx,ts,tsx,md,mdx}'],
  theme: {
    extend: {
      colors: { brand: 'var(--brand)', accent: 'var(--accent)', ink: 'var(--ink)', paper: 'var(--paper)' },
      fontFamily: { display: ['var(--font-display)'], body: ['var(--font-body)'] },
    },
  },
  plugins: [],
};
`;

// Design tokens as CSS custom properties — vibe-designer's palette/type lands here.
function tokensCss(tokens = {}) {
  const t = {
    brand: tokens.brand || '#4f46e5',
    accent: tokens.accent || '#f59e0b',
    ink: tokens.ink || '#0f172a',
    paper: tokens.paper || '#ffffff',
    fontDisplay: tokens.fontDisplay || "Georgia, 'Times New Roman', serif",
    fontBody: tokens.fontBody || "system-ui, -apple-system, Segoe UI, Roboto, sans-serif",
  };
  // Only allow a safe subset of chars into the token values (these are written into
  // CSS that the build serves) — defense against a hostile token from an imported brand.
  const clean = (v, fallback) => (/^[#a-zA-Z0-9 ,.'()\-_%]+$/.test(String(v)) ? String(v) : fallback);
  return `:root {
  --brand: ${clean(t.brand, '#4f46e5')};
  --accent: ${clean(t.accent, '#f59e0b')};
  --ink: ${clean(t.ink, '#0f172a')};
  --paper: ${clean(t.paper, '#ffffff')};
  --font-display: ${clean(t.fontDisplay, 'Georgia, serif')};
  --font-body: ${clean(t.fontBody, 'system-ui, sans-serif')};
}

@tailwind base;
@tailwind components;
@tailwind utilities;

html { color: var(--ink); background: var(--paper); font-family: var(--font-body); }
`;
}

const BASE_LAYOUT = `---
// Shared layout for EVERY page — header, nav, footer live here once. Pages import it.
import '../styles/tokens.css';
const { title = 'Untitled', description = '', og = {} } = Astro.props;
---
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>{title}</title>
    {description && <meta name="description" content={description} />}
    <meta property="og:title" content={og.title ?? title} />
    {(og.description ?? description) && <meta property="og:description" content={og.description ?? description} />}
    <meta name="twitter:card" content="summary_large_image" />
  </head>
  <body class="min-h-screen flex flex-col">
    <slot />
  </body>
</html>
`;

const INDEX_PAGE = `---
import Base from '../layouts/Base.astro';
---
<Base title="New Site" description="Generated by AI OS Web Studio">
  <main class="flex-1 grid place-items-center p-16 text-center">
    <div>
      <h1 class="text-5xl font-display text-brand">Your site is being built</h1>
      <p class="mt-4 text-lg opacity-70">The Web Studio team is composing your pages.</p>
    </div>
  </main>
</Base>
`;

/**
 * Write the Astro + Tailwind skeleton into a workspace dir.
 * @param {string} dir  workspace root, e.g. .magent/artifacts/web-studio/<siteId>
 * @param {{siteName?: string, tokens?: object}} opts
 * @returns {{dir, srcDir}}
 */
function scaffoldWorkspace(dir, opts = {}) {
  const src = path.join(dir, 'src');
  for (const d of ['layouts', 'pages', 'components', 'styles']) {
    fs.mkdirSync(path.join(src, d), { recursive: true });
  }
  fs.mkdirSync(path.join(dir, 'public'), { recursive: true });

  fs.writeFileSync(path.join(dir, 'package.json'), pkgJson(opts.siteName));
  fs.writeFileSync(path.join(dir, 'astro.config.mjs'), ASTRO_CONFIG);
  fs.writeFileSync(path.join(dir, 'tailwind.config.mjs'), TAILWIND_CONFIG);
  fs.writeFileSync(path.join(dir, '.gitignore'), 'node_modules/\ndist/\n.astro/\n');
  fs.writeFileSync(path.join(src, 'styles', 'tokens.css'), tokensCss(opts.tokens));
  fs.writeFileSync(path.join(src, 'layouts', 'Base.astro'), BASE_LAYOUT);
  fs.writeFileSync(path.join(src, 'pages', 'index.astro'), INDEX_PAGE);

  return { dir, srcDir: src };
}

module.exports = { scaffoldWorkspace, tokensCss };
