// tools/generate-maps.js — Vault Map + Skill Map generator
// The maps are the session-start table of contents: the Vault Map tells an agent
// how to navigate stored knowledge, the Skill Map tells it what capabilities exist.
// Run: npm run maps   (or required as a module by server.js getSessionContext)

const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');
const VAULT_DIR = path.join(ROOT, '.magent', 'vault');
const AGENTS_DIR = path.join(ROOT, '.claude', 'agents');
const SKILLS_DIR = path.join(ROOT, '.claude', 'skills');
const PIPELINES_DIR = path.join(ROOT, '.claude', 'pipelines');

const VAULT_MAP_PATH = path.join(VAULT_DIR, 'wiki', 'vault-map.md');
const SKILL_MAP_PATH = path.join(ROOT, '.claude', 'SKILL-MAP.md');

// Minimal frontmatter parser — handles the simple `key: value` style used in
// agent and skill files (no nested objects needed for the maps).
function parseFrontmatter(text) {
  const m = text.match(/^---\r?\n([\s\S]*?)\r?\n---/);
  if (!m) return {};
  const meta = {};
  for (const line of m[1].split(/\r?\n/)) {
    const kv = line.match(/^(\w[\w-]*):\s*(.+)$/);
    if (kv) meta[kv[1]] = kv[2].trim().replace(/^["']|["']$/g, '');
  }
  return meta;
}

function listMd(dir) {
  if (!fs.existsSync(dir)) return [];
  return fs.readdirSync(dir).filter(f => f.endsWith('.md'));
}

function buildVaultMap() {
  const lines = [
    '# Vault Map — Memory Navigation',
    '',
    '> Auto-generated by `npm run maps` — do not edit by hand. Read this first to locate knowledge instead of searching blind.',
    '',
    '| Folder | Purpose | When to read |',
    '|--------|---------|--------------|',
    '| `vault/raw/` | Unprocessed intake: clippings, dumps, extracted docs | Source material for synthesis tasks |',
    '| `vault/wiki/` | Synthesized knowledge: decision records, rosters, this map | Session start and before re-deriving anything |',
    '| `vault/outputs/` | Final deliverables already shipped | Before producing something similar — reuse, do not regenerate |',
    '',
  ];

  for (const folder of ['wiki', 'raw', 'outputs']) {
    const dir = path.join(VAULT_DIR, folder);
    const files = fs.existsSync(dir)
      ? fs.readdirSync(dir).filter(f => !f.startsWith('.')).sort()
      : [];
    lines.push(`## vault/${folder}/ (${files.length})`, '');
    if (!files.length) {
      lines.push('_(empty)_', '');
      continue;
    }
    for (const f of files) {
      if (f === 'vault-map.md') { lines.push(`- \`${f}\` — this file`); continue; }
      const fp = path.join(dir, f);
      let hint = '';
      if (f.endsWith('.md')) {
        const text = fs.readFileSync(fp, 'utf-8');
        const meta = parseFrontmatter(text);
        const heading = text.match(/^#\s+(.+)$/m);
        hint = meta.description || (heading ? heading[1] : '');
      }
      const mtime = fs.statSync(fp).mtime.toISOString().slice(0, 10);
      lines.push(`- \`${f}\` (${mtime})${hint ? ` — ${hint}` : ''}`);
    }
    lines.push('');
  }

  return lines.join('\n');
}

function buildSkillMap() {
  const lines = [
    '# Skill Map — Capability Inventory',
    '',
    '> Auto-generated by `npm run maps` — do not edit by hand. Consult this before assuming a capability is missing or building one that already exists.',
    '',
  ];

  // Agents grouped by their `group` frontmatter (fallback: core)
  const groups = {};
  for (const f of listMd(AGENTS_DIR)) {
    const meta = parseFrontmatter(fs.readFileSync(path.join(AGENTS_DIR, f), 'utf-8'));
    const group = meta.group || 'core';
    (groups[group] = groups[group] || []).push({
      name: meta.name || f.replace(/\.md$/, ''),
      model: meta.model || '',
      description: meta.description || '',
    });
  }
  const agentCount = Object.values(groups).reduce((n, g) => n + g.length, 0);
  lines.push(`## Agents (${agentCount}) — \`.claude/agents/\``, '');
  for (const group of Object.keys(groups).sort()) {
    lines.push(`### ${group}`, '');
    for (const a of groups[group].sort((x, y) => x.name.localeCompare(y.name))) {
      lines.push(`- **${a.name}** (${a.model}) — ${a.description}`);
    }
    lines.push('');
  }

  // Skills grouped by category
  const categories = {};
  for (const f of listMd(SKILLS_DIR)) {
    const meta = parseFrontmatter(fs.readFileSync(path.join(SKILLS_DIR, f), 'utf-8'));
    const cat = meta.category || 'general';
    (categories[cat] = categories[cat] || []).push({
      name: meta.name || f.replace(/\.md$/, ''),
      description: meta.description || '',
    });
  }
  const skillCount = Object.values(categories).reduce((n, c) => n + c.length, 0);
  lines.push(`## Skills (${skillCount}) — \`.claude/skills/\``, '');
  for (const cat of Object.keys(categories).sort()) {
    lines.push(`### ${cat}`, '');
    for (const s of categories[cat].sort((x, y) => x.name.localeCompare(y.name))) {
      lines.push(`- **${s.name}** — ${s.description}`);
    }
    lines.push('');
  }

  // Pipelines
  const pipelines = fs.existsSync(PIPELINES_DIR)
    ? fs.readdirSync(PIPELINES_DIR).filter(f => f.endsWith('.yaml') || f.endsWith('.yml')).sort()
    : [];
  lines.push(`## Pipelines (${pipelines.length}) — \`.claude/pipelines/\``, '');
  for (const f of pipelines) lines.push(`- \`${f}\``);
  lines.push('');

  return lines.join('\n');
}

function writeMaps() {
  fs.mkdirSync(path.dirname(VAULT_MAP_PATH), { recursive: true });
  fs.writeFileSync(VAULT_MAP_PATH, buildVaultMap());
  fs.writeFileSync(SKILL_MAP_PATH, buildSkillMap());
  return { vaultMap: VAULT_MAP_PATH, skillMap: SKILL_MAP_PATH };
}

module.exports = { buildVaultMap, buildSkillMap, writeMaps, VAULT_MAP_PATH, SKILL_MAP_PATH };

if (require.main === module) {
  const out = writeMaps();
  console.log('Vault map →', path.relative(ROOT, out.vaultMap));
  console.log('Skill map →', path.relative(ROOT, out.skillMap));
}
